name: Create Release with Wheel Files

on:
  push:
    branches:
      - main
    paths:
      - "packages/**/*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: 'ubuntu-latest'
    name: 'Build packages and create release'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'
      
      - name: 'Build packages'
        run: |
          ./build-packages --container-source=pull --container-tag=main --verbose --build-type packages-only
      
      - name: 'Create release tag'
        id: create_tag
        run: |
          # Create a unique tag based on date and short commit hash
          TAG="build-$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA:0:7}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag $TAG
          git push origin $TAG
      
      - name: 'Create release with wheel files'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          name: "Package Build ${{ steps.create_tag.outputs.tag }}"
          body: |
            Automated package build from commit ${{ github.sha }}
            
            Download wheel files and install on OT-2:
            ```bash
            # Download and install Prefect
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.create_tag.outputs.tag }}/prefect-3.3.4-py3-none-any.whl -o /tmp/prefect-3.3.4-py3-none-any.whl
            pip install /tmp/prefect-3.3.4-py3-none-any.whl
            ```
          files: |
            dist/*.whl
          draft: false
          prerelease: false